name: Admin - Bump Minor Version
on:
  pull_request:
    types: [closed]
    branches:
      - main
      - release/*/lts

jobs:
  bump:
    uses: kungfu-trader/workflows/.github/workflows/.bump-minor-version.yml@v1
    secrets:
      GITHUB_PUSH_TOKEN: ${{ secrets.KUNGFU_GITHUB_TOKEN }}
