name: Admin - Bump Major Version
on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type confirm to bump major version'
        required: true
        default: 'cancel'

jobs:
  bump:
    uses: kungfu-trader/workflows/.github/workflows/.bump-major-version.yml@v1
    secrets:
      GITHUB_PUSH_TOKEN: ${{ secrets.KUNGFU_GITHUB_TOKEN }}
