name: Release - Verify
on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - alpha/*/*
      - release/*/*
      - main

jobs:
  try:
    uses: kungfu-trader/workflows/.github/workflows/.release-verify.yml@v1
    with:
      enable-linux: true
      enable-macos: true
      enable-windows: true
    secrets:
      AWS_CI_ACCESS_KEY_ID: ${{ secrets.AWS_CI_ACCESS_KEY_ID }}
      AWS_CI_SECRET_ACCESS_KEY: ${{ secrets.AWS_CI_SECRET_ACCESS_KEY }}
      AWS_USER_ACCESS_KEY_ID: ${{ secrets.AWS_USER_ACCESS_KEY_ID }}
      AWS_USER_SECRET_ACCESS_KEY: ${{ secrets.AWS_USER_SECRET_ACCESS_KEY }}
      NODE_AUTH_TOKEN: ${{ secrets.KUNGFU_GITHUB_TOKEN }}

  verify:
    needs: try
    runs-on: ubuntu-22.04
    steps:
      - name: report
        run: echo verified
